config/routes.rb
Rails.application.routes.draw do
  
  resources :posts
  resources :users
  resources :comments

  root 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    validates :comment, presence: true
    belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, :content, presence: true
    validates :title, uniqueness: true
    belongs_to :user
    has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
    has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comment = Comment.all
    @comments = Post.find(params[:format]).comments
  end

  def new
    @comment = Comment.new
    session[:postID] = params[:format]
  end

  def show
  end

  def create
    @comment = Post.find(session[:postID]).comments.create(comment_params)
    if @comment.persisted? 
      redirect_to action: :index, controller: :posts
    else
      render :new
    end
  end

  def update
  end

  def edit
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to action: :index, controller: :posts 
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
    @posts = User.find(session[:postID]).posts
  end

  def new
    @post = Post.new
  end

  def show
  end

  def create
    #store data
    @post = User.find(session[:postID]).posts.create(post_params)
    if @post.persisted? 
      redirect_to :posts
    else
      render :new
    end

  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    
    redirect_to action: :index
  end

  def edit
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    
    redirect_to :posts
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
  end

  def show
  end

  def create
  end

  def update
  end

  def edit
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
<h1>Comments</h1>
<% @comments.each do |comment| %>
    <div class="card md-12 mb-3">
       <div class="card-body">
          <h4 class="card-title"><%= comment.content %></h4>
          <h6 class="card-title">for: <%= comment.post.title %></h6>
          <%= link_to  "delete", comment, method: :delete, class: "btn btn-danger" %>
       </div>
    </div>
 <% end %>

app/views/comments/new.html.erb
<%= render 'partial/commentForm'%>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="<%= root_path %>">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="<%= new_post_path %>">New Post <span class="sr-only">(current)</span></a>
        </li>
      </ul>
    </div>
  </nav>
  <div class="container">
    <%= yield %>
  </body>
</html>

app/views/partial/_commentForm.html.erb
<% if @comment.errors.any? %>
   <div class="alert alert-danger">
      <ul>
         <% @comment.errors.full_messages.each do |message| %>
            <li> <%= message %> </li>
         <% end %>
      </ul>
   </div>
<% end %>

<%= form_for(@comment, url: comments_path ) do |f| %>
   <div class="form-group">
      <%= f.text_area :comment, rows: "5", placeholder: "Content...", class: 'form-control' %>
   </div>
      <%= submit_tag params[:action] == 'new'? 'add': 'edit', class: 'btn btn-success btn-block' %>
<% end %>

app/views/partial/_postForm.html.erb
<% if @post.errors.any? %>
   <div class="alert alert-danger">
      <ul>
         <% @post.errors.full_messages.each do |message| %>
            <li> <%= message %> </li>
         <% end %>
      </ul>
   </div>
<% end %>

<%= form_for(@post, url: @post ) do |f| %>
   <div class="form-group">
      <%= f.text_field :title, placeholder: "Title...", class: 'form-control' %>
   </div>
   <div class="form-group">
      <%= f.text_area :content, rows: "5", placeholder: "Content...", class: 'form-control' %>
   </div>
      <%= submit_tag params[:action] == 'new'? 'Post': 'edit', class: 'btn btn-success btn-block' %>
<% end %>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<%= render 'partial/postForm'%>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
    <div class="card md-12 mb-3">
       <div class="card-body">
          <h4 class="card-title"><%= post.title %></h4>
          <h6 class="card-title"><%= post.user.name %></h6>
          <p class="card-text"><%= post.content %></p>
          <p class="card-text"> last update at: <%= post.updated_at %></p>
          <a href="<%= edit_post_path(post) %>" class="btn btn-primary">Edit</a>
          <%= link_to  "delete", post, method: :delete, class: "btn btn-danger" %>
          <a href="<%= new_comment_path(post) %>" class="btn btn-success">Comment</a>
       </div>
    </div>
 <% end %>

app/views/posts/new.html.erb
<h1> New Post </h1>
<%= render 'partial/postForm'%>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>